---
title: "Simulation"
author: "Jake Vettoretti"
date: "2025-10-30"
output: html_document
---

```{r}
library(tidyverse)
set.seed(1)
source("source/mean_and_sd.R")
source("source/sim_mean_sd.R")
```

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(30)
}

output |> 
  bind_rows() |> #stacks individual dataframe
  ggplot(aes(x=mu_hat)) +
  geom_density()
```

Try to repeat with map statement

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 90, 120),
    iter = 1:1000
) |> 
  mutate(
  results = map(sample_size, sim_mean_sd)
) |> 
  unnest(results)
```
Look at the results
```{r}
sim_results_df |> 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) |> 
  ggplot(aes(x=sample_size, y=mu_hat)) +
  geom_violin()
```
Let's try to summarize
```{r}
sim_results_df |> 
  group_by(sample_size) |> 
  summarize(
    emp_mean = mean(mu_hat),
    emp_se = sd(mu_hat)
  )
```
## Simple linear regression

```{r}
sim_df = 
    tibble(
      x = rnorm(30, mean = 1, sd = 1),
      y = 2+ 3* x + rnorm(30, 0, 1)
    )
sim_df |> 
  ggplot(aes(x=x,y=y))+
  geom_point()

slr_fit = lm(y~x, data=sim_df)
coef(slr_fit)
```


## Turn this into a function
```{r}
sim_regression = function(n_subj, beta_0 = 2, beta_1 = 3) {
  
  sim_df = 
    tibble(
      x = rnorm(n_subj, mean = 1, sd = 1),
      y = beta_0 + beta_1 * x + rnorm(n_subj, 0, 1)
    )

  slr_fit = lm(y~x, data=sim_df)
  tibble(
    beta0_hat = coef(slr_fit)[1],
    beta1_hat = coef(slr_fit)[2]
  )
}
```

```{r}
sim_regression(n_subj = 30)
```
Loop it
```{r}
output = vector("list", length = 500)

for (i in 1:500){
  output[[i]] = sim_regression(n_subj=30)
  
}

output |> 
  bind_rows()
```

```{r}
slr_sim_results_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:500
  ) |> 
  mutate(
    results = map(sample_size, sim_regression)
  ) |> 
  unnest(results)

slr_sim_results_df |> 
  ggplot(aes(x=beta0_hat, y = beta1_hat))+
  geom_point()
```

## One more example: birthday problem

```{r}
birthdays = sample(1:365, 5, replace = TRUE) #data generating mechanism

repeated_bday = length(unique(birthdays)) < 5 #checking if have same birthday
repeated_bday
```
```{r}
bday_sim = function(n_room){
  birthdays = sample(1:365, n_room, replace=TRUE)
  repeated_bday = length(unique(birthdays)) < n_room
  repeated_bday
}

bday_sim(20)
```

```{r}
bday_sim_results = 
  expand_grid(
    bdays = 5:50,
    iter = 1:2500
  ) |> 
  mutate(
    result = map_lgl(bdays, bday_sim) #returns logical vector
  ) |> 
  group_by(
    bdays
  ) |> 
  summarize(
    prob_repeat=mean(result)
  )

bday_sim_results
```

plot this

```{r}
bday_sim_results |> 
  ggplot(aes(x=bdays, y = prob_repeat))+
  geom_point() +
  geom_line()
```




